<h3>Cadastro de Contas</h3>
<hr />

<form class="form-horizontal" role="form" action="cadastraConta" method="POST">
	<div class="form-group">
		<div class="col-sm-5">
			<span class="glyphicon glyphicon-pencil"></span>
			<label>Descrição:</label>
			<input type="text" class="form-control" id="descricaoConta" name="descricaoConta" placeholder="Descrição" required="required" 
			value="<?php echo $_POST[descricaoConta]?>"/>
		</div>
	</div>

	<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
</form>