<h3>Cadastro de Grupos</h3>
<hr />

<form class="form-horizontal" role="from" action="#" method="POST">
	<div class="form-group">
		<div class="col-sm-5">
			<span class="glyphicon glyphicon-folder-open"></span>
			<label> Conta</label>
			<select class="form-control">
				<option>-Selecione-</option>
			</select>

			<br />

			<span class="glyphicon glyphicon-pencil"></span>
			<label> Descrição Grupo</label>
			<input type="text" class="form-control" placeholder="Descrição" id="descricaoGrupo" name="descricaoGrupo" required="required"/>
		</div>
	</div>
	
	<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Salvar</button>
</form>