<?php  
	use SON\Di\Container;
?>

<h3>Baixar Lançamento</h3>
<hr />

<div class="table-responsive" style="padding-right: 15px;">
	<table class="table table-striped table-hover table-condensed" id="myTable">
		<thead>
			<tr>
				<th style="text-align:center;">lancamentoId</th>
				<th style="text-align:center;">usuarioLancamento</th>
				<th style="text-align:center;">grupo</th>
				<th style="text-align:center;">dataLancamento</th>
				<th style="text-align:center;">valor</th>
				<th style="text-align:center;">descricao</th>
				<th style="text-align:center;">Ação</th>
			</tr>
		</thead>
		<tbody>
			<?php  
				foreach ($this->view->baixar as $key){
					#trata forma de a data ser printada (ao inves de 'yyyy-mm-dd' printa 'dd/mm/yyyy')
					$key[dataLancamento] = Container::trataData($key[dataLancamento]);

					echo ("
						<tr style=\"text-align:center;\">
							<td>$key[lancamentoId]</td>
							<td>$key[usuarioLancamento]</td>
							<td>$key[grupo]</td>
							<td>$key[dataLancamento]</td>
							<td>R$ $key[valor]</td>
							<td>$key[descricao]</td>
							<td>
								<button type=\"button\" class=\"btn btn-default\" title=\"Clique aqui para baixar o lançamento\" data-toggle=\"modal\" data-target=\"#myModal\" onclick=\"IniciaBaixa($key[lancamentoId],$_SESSION[usuarioId])\">
									<span class=\"glyphicon glyphicon-ok\"></span>
								</button>
							</td>
						</tr>
					");
				}
			?>
		</tbody>
	</table>
</div>

<!--modal para baixar os lancamentos-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel">Baixar Lançamento</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
	    $('#myTable').DataTable();
	});

	function IniciaBaixa(id,idUsuario){

		//monta modal
		$.ajax({
			type: "POST",
			url: "iniciaBaixa",
			data:{ 
				lancamentoId: id,
				usuarioId: idUsuario
			},
			success: function (retorno){
				$("#myModal .modal-dialog .modal-content .modal-body").html(retorno);
			}
		})

	}
</script>