<!DOCTYPE html>
<html>

	<head>
		<title>Altmer Web</title>

		<link rel="stylesheet" type="text/css" href="lib/bootstrap/css/bootstrap.min.css">

		<script src="lib/bootstrap/js/jQuery.js"></script>
		<script src="lib/bootstrap/js/bootstrap.js"></script>
		<?php require_once('topo.phtml'); ?>
	</head>

	<body>
		<div class="container">
			<?php 
				echo $this->content();
			?>
		</div>

	</body>

</html>